accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"
urlpatterns = [
     path('login/', login, name="login"),
     path('logout/', logout, name="logout"),
     path('signup/', signup, name="signup"),
]

main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [path('', mainpage, name="mainpage"),
path('second', secondpage, name="secondpage"),
path('new-post', new_post, name="new-post"),
path('create', create, name="create"),
path('<int:id>', detail, name="detail"),
path('edit/<int:id>', edit, name="edit"),
path('update/<int:id>', update, name="update"),
path('delete/<int:id>', delete, name="delete"),
path('delete_comment/<int:id>/', delete_comment, name='delete_comment'),
path('tag-list', tag_list, name="tag-list"),
path('tag-posts/<int:tag_id>', tag_posts, name="tag-posts"),
path('likes/<int:post_id>', likes, name="likes"),
     ]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
     path('mypage/<int:id>', mypage, name = "mypage"),
     path('follow/<int:id>', follow, name = "follow"),
] 

project/templates/shared/_footer.html
<footer>
     <p>멋쟁이사자처럼 13기 BE 권수현의 과제 페이지입니다.</p>
</footer>

project/templates/shared/_navbar.html
<nav class="navbar-container">
     <!--이미지 하나 넣기-->
     🌸
     <!-- mainpage 링크 연결-->
     <a class="navbar-link" href="{% url 'main:mainpage' %}">main</a>
     <!-- secondpage 링크 연결-->
     <a class="navbar-link" href="{% url 'main:secondpage' %}">Post</a>
     <a class="navbar-link" href="{% url 'main:tag-list' %}">Tag</a>
     <!-- git 링크 연결-->
     <a class="navbar-link" href="https://github.com/lo2q">git</a>
     🌸


     <!--사용자 인증 정보-->
     <div class="nav-right">
          {% if user.is_authenticated %}
          <!--로그인 시 보이는 화면-->
          <ul class="nav-link-account">
               <li class="nav-link-user">{{user.username}}</li>
               <li><a href="{% url 'accounts:logout' %}">로그아웃</a></li>
               <li><a href="{% url 'users:mypage' request.user.id %}">mypage</a></li>
          </ul>
          {% else %}
          <!--로그아웃 시 보이는 화면-->
          <ul class="nav=link-account">
               <li><a href="{% url 'accounts:login' %}">로그인</a></li>
               <li><a href="{% url 'accounts:signup' %}">signup</a></li>
          </ul>
          {% endif %}
     </div>
</nav>