main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [path('', mainpage, name="mainpage"),
path('second', secondpage, name="secondpage"),
path('new-post', new_post, name="new-post"),
path('create', create, name="create"),
path('<int:id>', detail, name="detail"),
path('edit/<int:id>', edit, name="edit"),
path('update/<int:id>', update, name="update"),
path('delete/<int:id>', delete, name="delete"),
path('delete_comment/<int:id>/', delete_comment, name='delete_comment'),
path('tag-list', tag_list, name="tag-list"),
path('tag-posts/<int:tag_id>', tag_posts, name="tag-posts"),
path('likes/<int:post_id>', likes, name="likes"),
     ]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
     path('mypage/<int:id>', mypage, name = "mypage"),
     path('follow/<int:id>', follow, name = "follow"),
] 

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import auth
from django.contrib.auth.models import User
from main.models import *

# Create your views here.
def mypage(request, id):
     user=get_object_or_404(User, pk=id)
     user_posts=Post.objects.filter(writer=user)
     context = {
          'user' :user,
          'user_posts' : user_posts,
     }
     return render(request, 'users/mypage.html', context)

def follow(request, id):
     user = request.user
     followed_user = get_object_or_404(User, pk=id)
     is_follower=user.profile in followed_user.profile.followers.all()
     if is_follower:
          user.profile.followings.remove(followed_user.profile)
     else:
          user.profile.followings.add(followed_user.profile)
     return redirect('users:mypage', followed_user.id)

users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>마이페이지에 오신 것을 환영합니다 🖤</h1>

<div class="profile-container">
     <div class="profile-info">
          <p><strong>사용자명:</strong> {{ user.username }}</p>
          <p><strong>소개:</strong> {{ user.profile.bio }}</p>
          <p><strong>전화번호:</strong> {{ user.profile.phone_number }}</p>
          <p><strong>생일:</strong> {{ user.profile.birth|date:"Y-m-d" }}</p>
     </div>
</div>

<hr>
<p>팔로워<br>{{ user.profile.followers.count}}명</p>
<p>팔로잉<br>{{ user.profile.followings.count}}명</p>

{% if request.user != user %}
{% if request.user.profile in user.profile.followers.all %}
<a href="{% url 'users:follow' user.id %}">
     <button type="button" class="btn btn-outline-info">언팔로우</button>
</a>
{% else %}
<a href="{% url 'users:follow' user.id %}">
     <button type="button" class="btn btn-info">팔로우</button>
</a>

{% endif %}
{% endif %}

<hr>

<h2>{{ user.username }}님이 작성한 글 목록</h2>
<div class="posts-container">
     {% if user_posts %}
     {% for post in user_posts %}
     <div class="post-item">
          <h3><a href="{% url 'main:detail' post.id %}">{{ post.title }}</a> - 오늘 기분 : {{ post.feeling }}</h3>

          <p>{{ post.writer }} | {% for tag in post.tags.all %}#{{ tag.name }}
               {% endfor %} | {{ post.created_at|date:"Y-m-d H:i" }}
          </p>
          <p>{{ post.summary }}</p>
          <hr>
     </div>
     {% endfor %}
     {% else %}
     <p>아직 작성한 글이 없습니다.</p>
     {% endif %}
</div>

{% endblock %}