main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [path('', mainpage, name="mainpage"),
path('second', secondpage, name="secondpage"),
path('new-post', new_post, name="new-post"),
path('create', create, name="create"),
path('<int:id>', detail, name="detail"),
path('edit/<int:id>', edit, name="edit"),
path('update/<int:id>', update, name="update"),
path('delete/<int:id>', delete, name="delete"),
path('delete_comment/<int:id>/', delete_comment, name='delete_comment'),
path('tag-list', tag_list, name="tag-list"),
path('tag-posts/<int:tag_id>', tag_posts, name="tag-posts"),
path('likes/<int:post_id>', likes, name="likes"),
     ]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
     path('mypage/<int:id>', mypage, name = "mypage"),
     path('follow/<int:id>', follow, name = "follow"),
] 

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Tag(models.Model) :
     name = models.CharField(max_length=30, null=False, blank=False)

     def __str__(self) :
          return self.name

class Post(models.Model):

     STATUS_CHOICES = [
          ('draft', '임시저장'),
          ('published', '발행'),
          ]
     
     title = models.CharField(max_length=50)
     writer = models.ForeignKey(User, null = False, blank = False, on_delete=models.CASCADE)
     feeling = models.CharField(max_length=50, blank=True)
     content = models.TextField()
     status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
     created_at = models.DateTimeField()
     image = models.ImageField(upload_to="post/", blank=True, null=True)
     tags = models.ManyToManyField(Tag, related_name='posts', blank=True)

     like = models.ManyToManyField(User, related_name='likes', blank=True)
     like_count = models.PositiveIntegerField(default=0)

     def __str__(self):
          return self.title
     
     def summary(self) :
          return self.content[:20]
     
class Comment(models.Model):
     content = models.TextField()
     pub_date = models.DateTimeField()
     writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
     post = models.ForeignKey(Post, null=False, blank=False, on_delete=models.CASCADE)

     def str (self):
          return self.post.title + " : " + self.content[:20] + "by" + self.writer.username

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .models import *

# Create your views here.

def mainpage(request) :
     return render(request, 'main/mainpage.html');

def secondpage(request) :
     posts = Post.objects.all()
     return render(request, 'main/secondpage.html', {'posts' : posts});


def new_post(request) :
     return render(request, 'main/new-post.html')

def delete_comment(request, id) :
     comment = get_object_or_404(Comment, pk = id)
     post_id = comment.post.id
     delete_comment = Comment.objects.get(pk=id)
     delete_comment.delete()
     return redirect('main:detail', post_id)

def detail(request, id) :
     post = get_object_or_404(Post, pk=id)
     if request.method =='GET':
          comments = Comment.objects.filter(post=post)
          return render(request, 'main/detail.html', {'post' : post, 'comments':comments})

     elif request.method == 'POST':
          new_comment = Comment()
          new_comment.post = post
          new_comment.writer = request.user
          new_comment.content = request.POST['content']
          new_comment.pub_date = timezone.now()
          new_comment.save()
          return redirect('main:detail', id)


def edit(request, id):
     edit_post = Post.objects.get(pk=id)
     return render(request, 'main/edit.html',  {"post": edit_post})

def update(request, id):
     update_post = Post.objects.get(pk=id)
     if request.user.is_authenticated and request.user == update_post.writer:
          update_post.title = request.POST['title']
          update_post.feeling = request.POST['feeling']
          update_post.content = request.POST['content']
          update_post.status = request.POST['status']
          update_post.created_at = timezone.now()

          if request.FILES.get('image'):
               update_post.image = request.FILES.get('image')

          update_post.tags.clear()
          lines = update_post.content.split('\n')
          tag_list = []
          for line in lines:
               words = line.split()
               for w in words:
                    if w.startswith('#') and len(w) > 1:
                         tag_list.append(w[1:])
          tag_list = list(set(tag_list))
          for t in tag_list:
               tag, _ = Tag.objects.get_or_create(name=t)
               update_post.tags.add(tag)

          update_post.save()
          return redirect('main:detail', update_post.id)
     return redirect ('accounts:login', update_post.id)

def delete(request, id):
     delete_post = Post.objects.get(pk=id)
     delete_post.delete()
     return redirect('main:secondpage')

def create(request):
     if request.user.is_authenticated:
          new_post = Post()

          new_post.title = request.POST['title']
          new_post.feeling = request.POST['feeling']
          new_post.content = request.POST['content']
          new_post.status = request.POST['status']
          new_post.created_at = timezone.now()
          new_post.image = request.FILES.get('image')
          new_post.writer=request.user
          new_post.save()

          lines = new_post.content.split('\n')
          tag_list = []

          for line in lines :
               words = line.split()
               for w in words:
                    if w.startswith('#') and len(w) > 1:  # '#'만 있는 경우 제외
                         tag_list.append(w[1:])  # '#' 제거 후 저장

          # 중복 제거
          tag_list = list(set(tag_list))

          for t in tag_list:
               tag, _ = Tag.objects.get_or_create(name=t)
               new_post.tags.add(tag)

          return redirect('main:detail', new_post.id)
     
     else:
          return redirect('accounts:login')
     
def tag_list(request):
     tags = Tag.objects.all()
     return render(request, 'main/tag-list.html', {'tags':tags})

def tag_posts(request, tag_id):
     tag=get_object_or_404(Tag, id=tag_id)
     posts=tag.posts.all()
     return render(request, 'main/tag-post.html', {
          'tag' : tag,
          'posts' : posts
     })

def likes (request, post_id):
     post = get_object_or_404(Post, id = post_id)
     if request.user in post.like.all():
          post.like.remove(request.user)
          post.like_count -=1
          post.save()

     else :
          post.like.add(request.user)
          post.like_count +=1
          post.save()
     
     return redirect ('main:detail', post.id)

main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h3>{{post.title}}</h3>
<a href="{% url 'users:mypage' post.writer.id %}"> 작성자 : {{post.writer}}</a>
<!-- 작성자 : {{post.writer}} / -->
/ 날짜 : {{post.created_at}} /
상태 : {{post.status}} /
오늘의 기분: {{ post.feeling }}
<br>
<p>
     {% for tag in post.tags.all %}
     <a href="{% url 'main:tag-posts' tag.id %}">#{{ tag.name }} </a>
     {% endfor %}
</p>
<hr>
<a href="{% url 'main:likes' post.id %}">
     {% if user in post.like.all %} 취소 {% else %} 좋아요 {% endif %}
</a>
{{post.like_count}}개


<hr />
{% if post.image %}
<p><img src="{{ post.image.url }}" alt="사진" width="100px"></p>
{% endif %}
<p>{{post.content}}</p>
{% if post.writer == user %}
<a href="{% url 'main:edit' post.id %}">글 수정하기</a>
<a href="{% url 'main:delete' post.id %}">삭제하기</a>
{% endif %}
<br>

<div class="comment_container">
     <div class="comment_form">
          <h2></h2>
          <form action="{% url 'main:detail' post.id %}" method="POST">
               {% csrf_token %}
               댓글 쓰기 : <input type="text" name="content">
               <input type="submit" name="submit">
          </form>
     </div>
     <div class="comment_list">
          {% for comment in comments %}
          <hr>
          <h4>작성자 : {{comment.writer}}</h4>
          <p>내용 : {{comment.content}}</p>
          <p>{{comment.pub_date}}</p>
          {% if comment.writer == user %}
          <a href="{% url 'main:delete_comment' comment.id %}">댓글 삭제</a>
          {% endif %}
          {% endfor %}
     </div>
</div>

{% endblock %}

main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>수정중...</h2>
<form action="{% url 'main:update' post.id %}" method="POST" enctype="multipart/form-data">
     {% csrf_token %}
     <p>제목: <input type="text" name="title" value="{{post.title}}"></p>
     <p>작성자: <input type="text" name="writer" value="{{post.writer}}"></p>
     <p>태그: <input type="text" name="tags" value="{{post.tags}}" style="width: 300px;"></p>
     <br>
     <p>감정: <input type="text" name="feeling" value="{{post.feeling}}" style="width: 300px;"></p>
     {% if post.image %}
     <p><img src="{{ post.image.url }}" alt="사진" width="100px"></p>
     {% endif %}
     <p>사진: <input type="file" name="image"></p>
     <p>내용: <textarea type="text" name="content" id="" cols="30" rows="10">{{post.content}}</textarea></p>
     <p>상태 :
          <select name="status">
               <option value="draft">임시저장</option>
               <option value="published" selected>발행</option>
          </select>
     </p>
     <button type="submit">제출</button>
</form>
{% endblock %}

main/templates/main/mainpage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>lo2q's week2 review</h1>

<h2>1. 1주차 세션 리뷰</h2>
<table border="1">
     <thead>
          <tr>
               <th>용어</th>
               <th>설명</th>
               <th>예시</th>
          </tr>
     </thead>
     <tbody>
          <tr>
               <td><strong>Project</strong></td>
               <td>사이트 전체</td>
               <td>인스타그램</td>
          </tr>
          <tr>
               <td><strong>App</strong></td>
               <td>프로젝트를 구성하는 기능의 집합</td>
               <td>회원정보, 게시글, DM(채팅) 등</td>
          </tr>
     </tbody>
</table>

<h2>2. 템플릿(Templates)이란?</h2>
<ul>
     <li>Django에서 사용자에게 보여줄 화면을 구성하는 HTML 역할</li>
     <li>보통 templates 폴더 안에 HTML 파일을 생성</li>
     <li>views.py에서 데이터를 전달받아 HTML을 렌더링함</li>
     <li>Django 템플릿 언어(DTL)를 사용하여 동적인 화면 구성 가능</li>
</ul>

<h2>3. 템플릿 사용해보기</h2>
<ol>
     <li>HTML, CSS 파일 작성</li>
     <li>views.py 작성</li>
     <li>urls.py 작성</li>
     <li>HTML 페이지와 view 연결</li>
</ol>

<h2>4. 템플릿 언어(Django Template Language, DTL)</h2>
<ul>
     <li>HTML 안에서 동적 데이터 처리 가능</li>
     <li>파이썬 문법을 기반으로 동작</li>
     <li>제공 기능: 변수 출력, 조건문, 반복문 등</li>
</ul>

<h3>템플릿 변수</h3>
<table border="1">
     <thead>
          <tr>
               <th>문법</th>
               <th>설명</th>
          </tr>
     </thead>
     <tbody>
          <tr>
               <td>&#123;&#123; 변수명 &#125;&#125;</td>
               <td>변수 출력</td>
          </tr>
          <tr>
               <td>&#123;&#123; 변수명.속성명 &#125;&#125;</td>
               <td>객체의 속성 출력</td>
          </tr>
          <tr>
               <td>&#123;&#123; list명.순서 &#125;&#125;</td>
               <td>리스트 인덱스 출력</td>
          </tr>
          <tr>
               <td>&#123;&#123; dict.key &#125;&#125;</td>
               <td>딕셔너리 키 값 출력</td>
          </tr>
     </tbody>
</table>
<h3>템플릿 태그</h3>
<table border="1">
     <thead>
          <tr>
               <th>문법</th>
               <th>설명</th>
          </tr>
     </thead>
     <tbody>
          <tr>
               <td>
                    &#123;% if 조건 %&#125;<br>
                    &#123;% else %&#125;<br>
                    &#123;% endif %&#125;
               </td>
               <td>조건문</td>
          </tr>
          <tr>
               <td>
                    &#123;% for item in list %&#125;<br>
                    &#123;&#123; item &#125;&#125;<br>
                    &#123;% endfor %&#125;
               </td>
               <td>반복문</td>
          </tr>
     </tbody>
</table>
<h2>5. 템플릿 상속이란?</h2>
<p>
     공통된 HTML 구조를 "부모 템플릿"으로 정의하고,<br>
     이를 "자식 템플릿"에서 확장하여 사용하는 방식이다.
</p>
<p>
     예를 들어, 여러 HTML 파일에서 동일하게 반복되는 head, nav bar 등은 하나의 부모 템플릿으로 만들고,<br>
     자식 템플릿에서 필요한 부분만 따로 작성하여 유지 보수와 재사용성을 높일 수 있다.
</p>
<ul>
     <li>&#123;% block content %&#125; : 블록 범위 시작</li>
     <li>&#123;% endblock %&#125; : 블록 범위 끝</li>
     <li>&#123;% extends 'base.html' %&#125; : base.html을 확장하겠다는 의미</li>
</ul>

<h2>6. static이란?</h2>
<p>
     웹 페이지에서 사용하는 CSS, 이미지 등 정적인 파일을 저장하는 디렉토리이다.
</p>
<p>
     static 파일을 HTML에서 사용하기 위해서는 다음과 같은 문법을 사용한다.
</p>
<ul>
     <li>&#123;% load static %&#125; : HTML 상단에 선언</li>
     <li>&lt;img src="&#123;% static 'images/파일명.확장자' %&#125;" alt=""&gt; : 이미지 파일 사용</li>
     <li>&lt;link rel="stylesheet" type="text/css" href="&#123;% static 'css/파일명.css' %&#125;"&gt; : CSS 포함
     </li>
</ul>
<p>
     또한 settings.py 파일에서 static 경로를 다음과 같이 설정해줘야 한다.
</p>
<ul>
     <li>STATICFILES_DIRS = [os.path.join(BASE_DIR, 'project', 'static')]</li>
     <li>STATIC_ROOT = os.path.join(BASE_DIR, 'static')</li>
</ul>

{% endblock%}

main/templates/main/new-blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form action="{% url 'main:create' %}" method="POST" enctype="multipart/form-data">
     {% csrf_token %}
     <p>제목 : <input type="text" name="title"></p>
     <p>작성자 : <input type="text" name="writer"></p>
     <p>사진: <input type="file" name="image"></p>
     <p>내용 : <textarea name="content" cols="30" rows="10"></textarea></p>
     <p>상태 :
          <select name="status">
               <option value="draft">임시저장</option>
               <option value="published">발행</option>
          </select>
     </p>
     <button type="submit">제출</button>
</form>
{% endblock %}

main/templates/main/new-post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form action="{% url 'main:create' %}" method="POST" enctype="multipart/form-data">
     {% csrf_token %}
     <p>제목: <input type="text" name="title"></p>
     <p>감정: <input type="text" name="feeling" placeholder="오늘의 감정을 한 줄로 입력해보세요!" style="width: 300px;"></p>
     <p>사진: <input type="file" name="image"></p>
     <p>내용: <textarea name="content" cols="30" rows="10"></textarea></p>
     <p>상태:
          <select name="status">
               <option value="draft">임시저장</option>
               <option value="published" selected>발행</option>
          </select>
     </p>
     <button type="submit">제출</button>
</form>
{% endblock %}

main/templates/main/secondpage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1 class="contents">2025 멋쟁이사자처럼 13기</h1>
<div>
     {% if user.is_authenticated %}
     <a href="{% url 'main:new-post'%}">새 글 작성하기</a>
     {% endif %}
</div>

<div class="contents"
     style="font-size: 20px; font-weight: 600; color: #333; padding: 8px 12px; border-bottom: 2px solid #ccc; margin-bottom: 16px;">
     Post List
</div>

<div>
     {% for post in posts %}
     <div>
          <h3>{{post.title}} - {{post.feeling}}</h3>
          {{post.writer}} |
          {% for tag in post.tags.all %}
          #{{ tag.name }}
          {% endfor %}
          | {{post.created_at}} <br>
          {{post.summary}}
          <a href="{% url 'main:detail' post.id %}">자세히 보기</a>
          <br><br>
          <hr />
     </div>
     {% endfor %}
</div>

{% endblock %}

main/templates/main/tag-list.html
{% extends 'base.html' %}
{% load static %}
{% block content %} <div>
     <h1>해시태그 목록</h1>
     <hr>
     {% for t in tags %}
     <div>
          <h2>
               <a href="{% url 'main:tag-posts' t.id %}">#{{t.name}}</a>
          </h2>
     </div>
     {% endfor %}
</div>
{% endblock %}

main/templates/main/tag-post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
     <h1>#{{tag}}가 달린 게시글</h1>
     <hr>
     <div>
          {% for p in posts %}
          <hr />
          <h3>{{p.title}}</h3>
          {{p.writer}} | {{p.pub_date}}<br>
          {{p.summary}}
          <a href="{% url 'main:detail' p.id %}">자세히 보기</a>
          <br>
          {% endfor %}
     </div>
</div>
{% endblock %}